### ISSUE TITLE
Is it compatible with rails(5.0.0.1)? 

### ISSUE THREAD

**Issue by Keerthi-harish** [mwalsher/actioncable-js#3]
We are creating video conference application and we use actioncable for transferring user data(identity) between backend and frontend. Recently we upgraded rails version(5.0.0beta3 to 5.0.0.1), after then we are getting the following error:

```
 Uncaught TypeError: Cannot read property 'received' of undefined
```

Thanks in advance.

**Comment by mwalsher** [comment]
I added a note to the top of the readme but will reiterate here. The Rails team has an official NPM package for ActionCable: https://www.npmjs.com/package/actioncable#npm-usage.
